### ISSUE TITLE
Docker container closes connection

### ISSUE THREAD

**Issue by mrusme** [fanzeyi/lares#1]
I'm trying to run lares using the following Docker command:

```
docker run --rm -it -p 127.0.0.1:4000:4000/tcp fanzeyi/lares 
```

when I run `telnet 127.0.0.1:4000` the connection seems to be dropped right away:

```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

Also when I try to connect with Reeder 4 for Mac it says:

<img width="431" alt="Screenshot 2020-09-11 at 8 26 20 PM" src="https://user-images.githubusercontent.com/151967/92965093-12aa8880-f46d-11ea-9c7d-c54981766974.png">

Is there anything else that is required for the Docker container to allow (and hold) incoming connections?

**Comment by mrusme** [comment]
After finding a workaround for #2 and trying the compiled binary locally everything seems to be working pretty damn fine. 👍🏼 Not sure though why the container drops the connection.

**Comment by fanzeyi** [comment]
@mrusme I think what happened was that Lares by default will only listen to local loopback (`127.0.0.1`) and as a result docker won't be exposing it. If you run it specifying the server host to 0.0.0.0 then it should work:

```
docker run --rm -it -p 127.0.0.1:4000:4000 fanzeyi/lares server --host 0.0.0.0
```
